In [1]:
import pandas

df = pandas.read_csv('data/BTC-USD.csv')

In [2]:
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100
...,...,...,...,...,...,...,...
3435,2024-02-12,48296.386719,50280.476563,47745.761719,49958.222656,49958.222656,34511985805
3436,2024-02-13,49941.359375,50358.390625,48406.496094,49742.441406,49742.441406,35593051468
3437,2024-02-14,49733.445313,52021.371094,49296.832031,51826.695313,51826.695313,39105608050
3438,2024-02-15,51836.785156,52820.066406,51371.628906,51938.554688,51938.554688,38564360533
3439,2024-02-16,51937.726563,52365.917969,51767.210938,51841.062500,51841.062500,35194347520

In [3]:
#Convert Date - Datetime set as index 
df['Date'] = pandas.to_datetime(df['Date'], format = "%Y-%m-%d")
df.set_index('Date', inplace = True)
df.head()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100

In [4]:
df.loc['2021-11-09']

Open         6.754973e+04
High         6.853034e+04
Low          6.638206e+04
Close        6.697183e+04
Adj Close    6.697183e+04
Volume       4.235799e+10
Name: 2021-11-09 00:00:00, dtype: float64

In [6]:
df1 = pandas.read_csv("bitcoin_price.csv",index_col = "Date", parse_dates = True )
df1.index

FileNotFoundError: [Errno 2] No such file or directory: 'bitcoin_price.csv'

In [ ]:
df1 = pandas.read_csv("bitcoin_price.csv",index_col = "Date", parse_dates = True )
df1.index

In [ ]:
df1 = pandas.read_csv("BTC-USD.csv",index_col = "Date", parse_dates = True )
df1.index

In [ ]:
df1 = pandas.read_csv("data/BTC-USD.csv",index_col = "Date", parse_dates = True )
df1.index

In [ ]:
df.resample('W').mean()